### PR TITLE
Gradient Tests

### PR DESCRIPTION
**Pull request by BillMills**
This PR contains first passes at the checks in #26 and #27. Notes:

 - Both follow the previous implementation of `Argo_spike_test.py` and its assumptions.
 - `WOD_gradient_check.py` adds a constraint that demands the depths of neighboring measurements not be identical (in order to avoid dividing by 0 in the gradient). But, the text mentions requiring neighboring measurements be separated by at least 3 m in the case of high-resolution instruments; that would also solve the divide-by-0 problem, but it isn't immediately clear to me if this constraint can be required generally, or, perhaps better, if and how the profile object indicates whether it was a 'high resolution' measurement or not.
 - Turned off the verbose logging temporarily, as the combinatorics grow. 
 - `WOD_gradient_check.py` also includes the check described in the text to attempt to distinguish between 0 as a number and 0 as a missing value indicator. Are we accommodating 0 as a missing value indicator? If not, might as well drop this part of the test.

### CODE REVIEW

**Comment by BoyerWOD** [comment]
Regarding WOD_gradient_check.py:
> you are correct, separation by 3m should preclude dividing by 0, but the way the 3m minimum works, if depths are less than 3m apart, a value of 3m is used to divide to get gradient/m.  If depths are exactly the same, this is often an indication of problem in the profile, already flagged in the depth inversion check, and the gradient check is skipped - in other words the flagging is dealt with in the depth variable not each individual oceanographic variable associated with that depth.  There is no need to classify an entire profile as high resolution, if two consecutive depths are within 3m, the < 3m criteria should be employed.
> We are not accommodating 0 as a missing value indicator, however, some of our data providers use 0.0 as a missing value without documenting it as such (or simply in error), so it is beneficial to differentiate, if possible, between real measurements of 0.0 and undocumented missing values.

**Comment by BillMills** [comment]
@BoyerWOD thanks! In that case:

 - if two depth measurements are less than 3 m separated, we'll treat them as 3 m apart.
 - the algorithm needs to not fall over when two consecutive depths are exactly the same. In light of what you mention about other tests flagging this scenario, there's no harm in not flagging it here (as is presently done).
 - we'll leave the 0-as-a-missing-data-indicator test in.

I'll implement these changes shortly, unless I hear otherwise.

**Comment by s-good** [comment]
Great! In addition, I noticed a couple of things about the levels that are being flagged:
* In line 36 I think that both qc[i] and qc[i+1] need to be set.
* in lines 40 and 42 I think the index should be i+1 rather than i

**Comment by BillMills** [comment]
that ought to do it - @s-good, I'll leave you to merge this if you think it's a good first pass; now that we have the facilities to build tests to check implementations of qc tests (#41, #45, #46), I'm happy merging this and validating properly in the test suite.

**Pull request merged**
