### PR TITLE
First functioning Docker build

### PR DESCRIPTION
**Pull request by BillMills**
AutoQC now has its own functioning Docker container: https://hub.docker.com/r/billmills/autoqc/

This makes installing AutoQC and all its dependencies (including extra data) very easy (see instructions in the `README`), particularly on cloud services like AWS - setup there used to be quite complicated (see #105), but can now be done in a single script (which is also much faster than the previous setup process).

Things still to do:

 - ~~Validate dependencies. All tests pass in the docker container, but there might be some unnecessary things installed per discussion in #120~~
 - ~~Migrate travis testing. The current `travis.yml` is a bit of a mess; the Docker setup is much simpler, and guarantees we are testing and running in the *exact* same environment. Will look into moving travis testing shortly.~~
 - ~~Performance test. The internet nigh-unanimously believes that Docker is every bit as fast as native, but given the length of the full AutoQC calculation, we'd best check before we sign off on this once and for all.~~

### CODE REVIEW

**Comment by BillMills** [comment]
Alright - about 10k profiles from *quota* ran in the docker container actually slightly *faster* than natively - probably an artefact and not a real speed-up, but good enough to convince me the claims of no performance hits are credible. Also of course, the resulting csv was character-for-character identical in both cases.

I'm going to merge this once #125 is resolved, and make sure any dependencies introduced there are reflected in the docker image. Should probably make an image `iquod/autoqc` instead of `billmills/autoqc`, too.

**Comment by BillMills** [comment]
@s-good as promised, this all checks out - the only thing left to do is I'm sure you'd like the image to be called `iquod/autoqc` and not `billmills/autoqc` - if you could make a [Dockerhub](https://hub.docker.com/) account with username `iquod`, you should be able to create an empty project and give me commit rights to it, so we can push the image there and wrap this up.

**Comment by BillMills** [comment]
(also notice the travis tests are way faster now, too :)

**Comment by BillMills** [comment]
oh actually @s-good - it looks like there are organization accounts on dockerhub as well, so I can make one for iquod and invite you if you like, no need to make the iquod user account like I first thought.

**Comment by s-good** [comment]
Hi @BillMills I'd already gone ahead and made the account but I've converted it to an organisation and have added you so hopefully all is OK.

**Comment by BillMills** [comment]
No problem, it seems to have worked just fine; I'll change everything in this PR to point at the new image, triple-check it all works and we can merge - thanks, this is going to be great!

**Comment by BillMills** [comment]
Alright that's got it - to recap:

 - we now have all our dependencies encapsulated in the [iquod/autoqc docker image](https://hub.docker.com/r/iquod/autoqc/)
 - this greatly speeds up and simplifies setup on Travis and AWS
 - prevents missing data problems like we wrestled with in #125 
 - ensures testing on Travis is done in the *exact* same environment as running on AWS or locally
 - guarantees we can reproduce the dependency stack on any machine at any time in the future.

Dependency details are now in `docker/Dockerfile`; this is now the 'master list' of our dependency stack, and any future dependency changes need to be reflected there.

I will be writing a wiki page on how to do fancier things on AWS with our docker container (like mounting an S3 directory with all our data into the docker container), but for now basic usage instructions can be found in the `README` - let me know any hiccups.

**Comment by s-good** [comment]
Looks really nice - thanks for doing this!

**Pull request merged**
