### PR TITLE
en_stability fallback

### PR DESCRIPTION
**Pull request by katieannemills**
@s-good - here's about the simplest possible attempt at #281, let me know if we're looking for something more sophisticated.

### CODE REVIEW

**Comment by s-good** [comment]
Thanks for working on this. Another alternative is to use the function p_from_z() from gsw (https://teos-10.github.io/GSW-Python/conversions.html) which we use already in a number of places in AutoQC. I expect there is little difference between them, though. @BoyerWOD, do you have a preference between these?

**Comment by BillMills** [comment]
Oh good point @s-good, we should use the gsw implementation and not add dependencies, unless there's a really good reason to add them - let me know what you and @BoyerWOD decide.

**Comment by BoyerWOD** [comment]
TEOS-10 is probably best choice since it supersedes EOS-80.  I dont expect differences between the two would be noticeable in a stability check

**Review by s-good — APPROVED** [review]
Thanks - this looks great to me!

**Comment by BillMills** [comment]
terrific - I want to get the CI test suite migrated to GH actions and running again before we merge here; I'll have time for that on Sunday and we can merge.

**Comment by BillMills** [comment]
After fussing with migrating from travis to ghactions to get out unit testing back online, I noticed we actually have a helper for converting depth to pressure we use everywhere else. It's the exact same TEOS-10 via gsw as before, but changed to use it just for internal consistency. I'm going to go ahead and merge here, as always please let me know any further problems or requests.

**Pull request merged**
