### PR TITLE
Update CoTeDe_fuzzy_logic.py

### PR DESCRIPTION
**Pull request by s-good**
Fuzzy logic config should be picked up from CoTeDe after this change. Config files in AutoQC should now be superfluous.

### CODE REVIEW

**Comment by s-good** [comment]
It's not clear why this is not working. Could the version of CoTeDe that is in use not include the fuzzylogic config file? Will need to remove some of the try, except statements to check exactly where it is going wrong.

**Comment by BillMills** [comment]
Travis complains that:

```
IOError: [Errno 2] No such file or directory: 'cotede_qc/qc_cfg/fuzzylogic.json'
```

which judging by the path is one of the CoTeDe config files that ships with AutoQC. And, it's right - there is no `fuzzylogic.json` in that directory in the current HEAD of AutoQC; but, there is a `fuzzy.json`; could this just be a naming mixup? @s-good, do you have the `fuzzylogic.json` file on your machine (allowing the tests to pass locally but not remotely)?

**Comment by s-good** [comment]
The latest version of the code looks in CoTeDe for the config file first (where it is called fuzzylogic, not logic) and then tries in the AutoQC cotede_qc/qc_cfg directory if that fails. In this latest version the files in the AutoQC cotede_qc/qc_cfg directory should not be needed at all. My suspicion is that we are not picking up the latest version of CoTeDe. Could it be because the docker image needs updating?

**Comment by BillMills** [comment]
Hi @s-good,

 - What version of CoTeDe do you have? The Docker container currently has 0.17.2, which seems to have been stable for some time now.
 - looking in `qc_cfg/cotede_test.py`, in the try/catch where we go looking for the config file from CoTeDe, there is the following attempt to load the file from CoTeDe:

```
        # If config is a dictionary, use it.
        if type(config) is not dict:
            try:
                # Load config from CoTeDe
                cfg = load_cfg(config)
```

Sorry if I'm just being super dense, but the function `load_cfg` doesn't seem to be defined anywhere, which would result in failing the try and the behavior you've observed. Did something not get checked in somewhere?

**Comment by BillMills** [comment]
Or - wait, that `load_cfg` function was the import problem you metioned [here](https://github.com/IQuOD/AutoQC/commit/7ae18cf1a66fb0dfca7bbe0240ac3fbab8a66f5f). Adding that in still produces a lot of key errors for me:

```
root@f24156995537:/AutoQC# nosetests tests/CoTeDe_checks_validation.py
...F..EEEE.EE.E
======================================================================
ERROR: Make sure CoTeDe gradient is working as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 73, in test_CoTeDe_GTSPP_gradient
    qc = qctests.CoTeDe_GTSPP_gradient.test(p)
  File "/AutoQC/qctests/CoTeDe_GTSPP_gradient.py", line 9, in test
    return get_qc(p, config, testname)
  File "/AutoQC/cotede_qc/cotede_test.py", line 69, in get_qc
    qc_returned = cotede_results[2].flags[var][test]
KeyError: 'gradient'

======================================================================
ERROR: Make sure CoTeDe spike check is working as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 81, in test_CoTeDe_GTSPP_spike_check
    qc = qctests.CoTeDe_GTSPP_spike_check.test(p)
  File "/AutoQC/qctests/CoTeDe_GTSPP_spike_check.py", line 9, in test
    return get_qc(p, config, testname)
  File "/AutoQC/cotede_qc/cotede_test.py", line 69, in get_qc
    qc_returned = cotede_results[2].flags[var][test]
KeyError: 'spike'

======================================================================
ERROR: Make sure CoTeDe location at sea test is working as expected when given an ocean location.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 97, in test_CoTeDe_location_at_sea_test_ocean_point
    qc = qctests.CoTeDe_location_at_sea_test.test(p)
  File "/AutoQC/qctests/CoTeDe_location_at_sea_test.py", line 9, in test
    return get_qc(p, config, testname)
  File "/AutoQC/cotede_qc/cotede_test.py", line 69, in get_qc
    qc_returned = cotede_results[2].flags[var][test]
KeyError: 'TEMP'

======================================================================
ERROR: Make sure CoTeDe location at sea test is working as expected when given a land location.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 112, in test_CoTeDe_location_at_sea_test_land_point
    qc = qctests.CoTeDe_location_at_sea_test.test(pland)
  File "/AutoQC/qctests/CoTeDe_location_at_sea_test.py", line 9, in test
    return get_qc(p, config, testname)
  File "/AutoQC/cotede_qc/cotede_test.py", line 69, in get_qc
    qc_returned = cotede_results[2].flags[var][test]
KeyError: 'TEMP'

======================================================================
ERROR: Make sure CoTeDe rate_of_change is working as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 128, in test_CoTeDe_rate_of_change
    qc = qctests.CoTeDe_rate_of_change.test(p)
  File "/AutoQC/qctests/CoTeDe_rate_of_change.py", line 9, in test
    return get_qc(p, config, testname)
  File "/AutoQC/cotede_qc/cotede_test.py", line 69, in get_qc
    qc_returned = cotede_results[2].flags[var][test]
KeyError: 'rate_of_change'

======================================================================
ERROR: Make sure CoTeDe spike is working as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 136, in test_CoTeDe_spike
    qc = qctests.CoTeDe_spike.test(p)
  File "/AutoQC/qctests/CoTeDe_spike.py", line 9, in test
    return get_qc(p, config, testname)
  File "/AutoQC/cotede_qc/cotede_test.py", line 69, in get_qc
    qc_returned = cotede_results[2].flags[var][test]
KeyError: 'spike'

======================================================================
ERROR: Make sure CoTeDe WOA normbias is working as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 155, in test_CoTeDe_WOA_normbias
    qc = qctests.CoTeDe_WOA_normbias.test(p)
  File "/AutoQC/qctests/CoTeDe_WOA_normbias.py", line 9, in test
    return get_qc(p, config, testname)
  File "/AutoQC/cotede_qc/cotede_test.py", line 69, in get_qc
    qc_returned = cotede_results[2].flags[var][test]
KeyError: 'woa_normbias'

======================================================================
FAIL: Make sure CoTeDe fuzzy logic is working as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/AutoQC/tests/CoTeDe_checks_validation.py", line 50, in test_CoTeDe_fuzzy_logic
    assert np.array_equal(qc, expected_qc_fuzzy_logic), 'mismatch between qc results and expected values'
AssertionError: mismatch between qc results and expected values
-------------------- >> begin captured stdout << ---------------------
Deprecated cfg format. It should contain a threshold item.
Deprecated cfg format. It should contain a threshold item.

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 15 tests in 2.277s

FAILED (errors=7, failures=1)
```

**Comment by s-good** [comment]
These should have been sorted out in the changes in #175? The build is currently passing.

I reran the tests for this fuzzylogic changing test and one of the tests is now finding the fuzzylogic.json file from CoTeDe (tests still fail as the QC results are not the same) and the other one is still failing to find it.

**Comment by s-good** [comment]
I think I have worked out the reason for the woa_normbias key error in #173. I will comment there. I will come back to this pull request once this is sorted. As noted above, the QC results appear to have changed for this QC tests because there are differences between the current fuzzylogic.json config file and the previous version fuzzy.json (there is a copy of this in the AutoQC cotede_qc/qc_cfg directory). There is also now a very similar config file called morello2014.json in CoTeDe. I will find out which we should use (or both) and modify the tests accordingly.

**Comment by s-good** [comment]
NB I have an open CoTeDe pull request to get rid of the deprecated cfg format warnings that have appeared above after the fuzzy logic test (https://github.com/castelao/CoTeDe/pull/29).

**Comment by BillMills** [comment]
Excellent, thanks for sorting this @s-good - and re: my big pile of errors above, you're right, #175 solves this - I was confused since the `Fuzzy-logic-from-CoTeDe` branch doesn't contain the commits added in #175. Anyway, sounds like we just need to make sure we're pointing at the right config file - thanks for sorting this out!

**Comment by s-good** [comment]
I've updated the tests and added the new Morello 2014 test. Build now passes so will merge.

**Pull request merged**
