### PR TITLE
Update to allow a config to be passed direct to the cotede_test.get_q…

### PR DESCRIPTION
**Pull request by s-good**
…c function as well as a config file. This should correct the problem with the failing build.

### CODE REVIEW

**Comment by BillMills** [comment]
Note this will fail, because it is checking the failing master branch - not the patched branch you want to check. I have a fix for the build system coming momentarily, after which we can re-run this check and it ought to pass.

**Comment by BillMills** [comment]
As mentioned in #128, going to merge here and hopefully that solves everything - if not, we can reassess what's still wrong.

**Comment by BillMills** [comment]
Build still breaking but with different (and much fewer) errors - will attempt to fix.

**Comment by s-good** [comment]
I think this may be due to the version of cotede. I'm not sure if my attempt to set the version in the docker file is working.

**Comment by BillMills** [comment]
ah, great idea - remember, its not enough to just change the Dockerfile; if the deps change, we actually have to rebuild the image and push to dockerhub. I will do that now.

**Comment by s-good** [comment]
Ah, OK - will do that in future. Thanks for sorting this.

**Comment by BillMills** [comment]
Alright, works on my machine - new image is pushing now and will hopefully resolve all problems. Sorry for this - the janky travis.yml that started this was my fault. Transitioning to new infrastructure is bumpy at first but pays off once the dust settles.

**Comment by BillMills** [comment]
Yep confirmed, that's got it; will triple check the build infrastructure right now to make sure no more funny business is waiting for us.

**Comment by BillMills** [comment]
And meta-confirmed: if I break my own build, the latest travis.yml catches it properly, unlike what happened with #126.

**Pull request merged**
