### PR TITLE
minmax

### PR DESCRIPTION
**Pull request by BillMills**
Here's an implementation of minmax, from our colleagues at Oceanscope. A few thoughts on the first draft:

 - The helper functions provided by the original authors are included verbatim. Some simplification might be possible since that implementation folded running over lists of profiles into the test logic, whereas AutoQC factors this out.
 - Unit tests are currently somewhat minimal and could do with some expansion. Currently they check that the temperature mins and maxes and the final QC results come out the same in this implementation as they did in the example provided by the authors for the first profile in their example dataset. That's a good start, but I'd like to see checks on edge cases and more pathological profiles as well, including exception handling around missing data.
 - QC runs and tests pass in the environment described by the container image `iquod/autoqc:1.0-rc3`, with the following modifications:
   - upgrade pandas -> 1.1.4
   - install xarray at 0.16.1
   - copy original author's parameter files into `/AutoQC/data`
   I haven't posted this environment anywhere yet as @s-good mentioned we may need to discuss proper attribution before we distribute those parameter files. Perhaps a DOI should be created for them if feasible?
 - Domain experts: I wonder if it's possible to re-write this to not rely on salinity data, so that we can successfully run this test on profiles that only have temperature, depth, lat and long available. The only thing the salinity data object seems to be getting used for is its depth profile; perhaps we could take that elsewhere and do away with salinity considerations.

Let me know any thoughts on the above or the implementation included, and we can correct from there.

### CODE REVIEW

**Comment by BillMills** [comment]
Many thanks to Rachel Killick for the testing, comments and implementation in 713269a!

**Comment by BillMills** [comment]
Tests are now passing for minmax in image `iquod/autoqc:1.0-rc4`; the fails reported by CI are all actually CoTeDe fails, which are already resolved in #261.

I also include here an outline of a `REFERENCES.md` where we can list DOIs and other citations; CoTeDe and Wodpy have obvious DOIs to cite and minmax's code will also have one shortly per our discussion with Jerome. @s-good let me know what you think would be best for citing everyone else (AOML, CSIRO, ICDC and others).

**Comment by s-good** [comment]
The draft paper contains the full list of citations for all the QC checks. We could either link to the paper once it is published or take the information from the paper and put it into a table. 

Should we merge this pull request and open a new issue to sort this?

**Comment by BillMills** [comment]
Hi @s-good - you're right, let's leave the references out for now and link the paper once it's published; better to have one list in one place then reproduce everywhere.

In that case, I'll go ahead and merge here; let me know anything I can do to help get this paper over the finish line!

**Pull request merged**
