### PR TITLE
new install scripts

### PR DESCRIPTION
**Pull request by BillMills**
work in progress

Here's the start of a refresh of our install paths.

Questions for @s-good:

 - ~I've started building this around Ubuntu 16.04, but I'm not really attached to this at all; if you have a preferred linux distro, let me know and I'm sure we can accommodate.~ *Ubuntu 16.04 it is.*
 - The one step that isn't 100% automated yet is the provisioning of all the parameter files in `/AutoQC/data`; have a look in `install.sh`, and you'll see that some of them are downloaded while others are marked TBD. Is there a sensible place we can zip up and host all the parameter files AutoQC needs?

Work still to do before merge:

 - Address the above questions
 - ~Make sure Travis is able to ingest, run and pass tests in this new environment~ *tests passing in travis on our new stack.*
 - ~Consider migrating to Python 3.5 as the default python version for AutoQC (this currently provisions 2.7 still, which is getting quite old...)~ *I still want to do this, but it's a big enough rabbithole that it should be done in its own PR.*
 - ~Run a shakedown on @s-good's 10k profiles to ensure no surprises.~ *Looks clean in a bare install on AWS, as well as in the corresponding container.*

### CODE REVIEW

**Comment by s-good** [comment]
Thanks for doing this. I don't have a strong preference for linux distribution, but Ubuntu and the other distributions that are based on it are very popular so it sounds a good choice.

For storing the files, a good place to serve them from could be the WOD site - @BoyerWOD, would this be possible?

**Comment by BillMills** [comment]
Note the last commit pins all the python packages to their current version numbers. I am in general a big fan of pinning version numbers for the sake of reproducibility; I chose not to pin the underlying system-level packages at this time though, as those get distro- and package manager-specific, and would cause a lot of friction for folks who want to migrate off of ubuntu. However, at a minimum `numpy` must be pinned to at or about 1.11.3, or cotede starts throwing a lot of additional errors.

**Comment by BillMills** [comment]
OK, all my above concerns have been addressed except for the parameter file hosting issue, but things seem to be working correctly in an environment described by `install.sh`. For those looking for a usable preview of this environment while we resolve the parameter file issue, have a look at the `iquod/autoqc:ubuntu-16.04` docker image, or set up directly on an ubuntu 16.04 host (tested successfully on AWS).

**Comment by BoyerWOD** [comment]
Sorry, just back from holiday.  The two parameter file hosting questions I see in install.sh are the following:
+# TBD climatological_t_median_and_amd_for_aqc.nc
 +# TBD all four of the woa13_decav_s[13-16]_5dv2.nc

That second one lists a set of files which is already on our thredds server:
https://data.nodc.noaa.gov/thredds/catalog/woa/WOA13/DATAv2/salinity/netcdf/decav/5deg/catalog.html

The first one I dont recognize.  Where does that come from?  We would have to archive it here at NCEI to post it to our thredds server.  This is probably a good idea anyway if it is not archived anywhere.  We could also keep track of updates to the qc system this way.

**Comment by BillMills** [comment]
Right you are @BoyerWOD, thanks for that; I've pointed the install script at the salinity data you mention on thredds.

`climatological_t_median_and_amd_for_aqc.nc` I believe came from Viktor Gouretski to support the ICDC suite of tests; I'm not sure if this was ever hosted anywhere reachable. @s-good, do you recall the same?

**Comment by s-good** [comment]
In the [install mkl line](https://github.com/IQuOD/AutoQC/blob/5837c5c8c9de41aba0afec56fa0a23af4d2b605d/install.sh#L27) it asks for 2018.0.1 but pip is only able to find 2018.0.0 or 2018.0.3. Is 2018.0.3 OK to use?

**Comment by s-good** [comment]
Also, I just noticed that CoTeDe downgrades numpy and scipy to numpy-1.11.1 and scipy-0.18.0 when it is installed.

**Comment by BillMills** [comment]
@s-good are you running `install.sh` literally (like `bash install.sh`), or are you trying to install the listed packages manually? As you've discovered, install order matters, and can break things.

If I run `install.sh` in an ubuntu 16.04 container, I get a functioning build with the final packages listed below; the same should be true without a container, on an ubuntu 16.04 host, and I'll confirm that shortly.

I end up with the following installed by `install.sh`:

`conda list`:
```
# packages in environment at /AutoQC/miniconda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0  
backports                 1.0                      py27_1  
backports.functools_lru_cache 1.5                      py27_1  
backports_abc             0.5                      py27_0  
blas                      1.0                    openblas  
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py27_0  
cffi                      1.11.5           py27h9745a5d_0  
chardet                   3.0.4            py27hfa10054_1  
conda                     4.5.9                    py27_0  
conda-env                 2.6.0                h36134e3_1  
cotede                    0.18.0                    <pip>
cryptography              2.2.2            py27h14c3975_0  
curl                      7.61.0               h84994c4_0  
cycler                    0.10.0                   py27_0  
dbus                      1.13.2               hc3f9b76_0  
decorator                 4.3.0                     <pip>
enum34                    1.1.6            py27h99a27e9_1  
expat                     2.2.5                he0dffb1_0  
filelock                  3.0.4                     <pip>
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  hab7d2ae_1  
functools32               3.2.3.2                  py27_1  
futures                   3.2.0            py27h7b459c0_0  
geos                      3.6.2                heeff764_2  
glib                      2.53.6               h5d9569c_2  
gst-plugins-base          1.12.4               h33fb286_0  
gstreamer                 1.12.4               hb53b477_0  
gsw                       3.0.3                     <pip>
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.1               h9caa474_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py27h5722d68_1  
intel-openmp              2018.0.3                      0  
ipaddress                 1.0.22                   py27_0  
jpeg                      9b                   h024ee3a_2  
libcurl                   7.61.0               h1ad7b7a_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libnetcdf                 4.4.1.1              h816af47_8  
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               hb9fc6fc_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              7.2.0                hdf63c60_3  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
matplotlib                2.1.1            py27h0128e01_0  
mkl                       2018.0.1             h19d6760_4  
ncurses                   6.1                  hf484d3e_0  
netcdf4                   1.3.1            py27hca9ce0b_2  
networkx                  2.1                       <pip>
nose                      1.3.7                    py27_2  
numpy                     1.11.3           py27h2aefc1b_9  
numpy-base                1.11.3           py27h7cdd4dd_9  
oceansdb                  0.6.0                     <pip>
openblas                  0.2.19                        0  
openssl                   1.0.2o               h14c3975_1  
pandas                    0.21.1           py27h38cdd7d_0  
pcre                      8.42                 h439df22_0  
pip                       10.0.1                   py27_0  
proj4                     5.0.1                h14c3975_0  
pycosat                   0.6.3            py27ha4109ae_0  
pycparser                 2.18             py27hefa08c5_1  
pyopenssl                 18.0.0                   py27_0  
pyparsing                 2.2.0                    py27_1  
pyproj                    1.9.5.1          py27h7b21b82_1  
pyqt                      5.6.0            py27h22d08a2_6  
pysocks                   1.6.8                    py27_0  
python                    2.7.15               h1571d57_0  
python-dateutil           2.7.3                    py27_0  
pytz                      2018.5                   py27_0  
qt                        5.6.2               hd25b39d_14  
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py27hc5b0589_1  
ruamel_yaml               0.15.37          py27h14c3975_2  
scikit-fuzzy              0.3                       <pip>
scipy                     0.19.0          np111py27_nomkl_0  [nomkl]
seabird                   0.8.0                     <pip>
setuptools                39.2.0                   py27_0  
shapely                   1.6.2            py27hd647e55_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18.1           py27hf484d3e_2  
six                       1.11.0           py27h5f960f1_1  
sqlite                    3.23.1               he433501_0  
subprocess32              3.5.2            py27h14c3975_0  
tk                        8.6.7                hc745277_3  
tornado                   5.0.2            py27h14c3975_0  
urllib3                   1.22             py27ha55213b_0  
wheel                     0.31.1                   py27_0  
wodpy                     1.5.0                     <pip>
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               ha838bed_2 
```

and `pip freeze`:
```
asn1crypto==0.24.0
backports-abc==0.5
backports.functools-lru-cache==1.5
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
conda==4.5.9
cotede==0.18.0
cryptography==2.2.2
cycler==0.10.0
decorator==4.3.0
enum34==1.1.6
filelock==3.0.4
functools32==3.2.3.post2
futures==3.2.0
gsw==3.0.3
idna==2.6
ipaddress==1.0.22
matplotlib==2.1.1
netCDF4==1.3.1
networkx==2.1
nose==1.3.7
numpy==1.11.3
oceansdb==0.6.0
pandas==0.21.1
pycosat==0.6.3
pycparser==2.18
pyOpenSSL==18.0.0
pyparsing==2.2.0
pyproj==1.9.5.1
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
requests==2.18.4
ruamel-yaml==0.15.37
scikit-fuzzy==0.3
scipy==0.19.0
seabird==0.8.0
Shapely==1.6.2
singledispatch==3.4.0.3
six==1.11.0
subprocess32==3.5.2
tornado==5.0.2
urllib3==1.22
wodpy==1.5.0
```

**Comment by BillMills** [comment]
@s-good per your suggestion, I've updated `install.sh` to be a bit more virtualenv friendly and not rely on conda; running that install script in an ubuntu:16.04 container produces exactly the `pip freeze` package list you sent me from your environment:

```
backports.functools-lru-cache==1.5
cotede==0.18.0
cycler==0.10.0
decorator==4.3.0
filelock==3.0.4
gsw==3.0.3
intel-openmp==2018.0.3
matplotlib==2.1.1
mkl==2018.0.3
netCDF4==1.3.1
networkx==2.1
nose==1.3.7
numpy==1.11.3
oceansdb==0.6.0
pandas==0.21.1
pyparsing==2.2.0
pyproj==1.9.5.1
python-dateutil==2.7.3
pytz==2018.5
scikit-fuzzy==0.3
scipy==0.19.0
seabird==0.8.0
Shapely==1.6.2
six==1.11.0
subprocess32==3.5.2
wodpy==1.5.0
```

So, we've got a nominally reproducible environment; I ran over 10 whole profiles just to make sure things don't instantly fall over, and it went fine. I'd still like to try tweaking numpy and scipy versions to see if we can make those cotede install warnings go away; then we can do staging runs over a more substantial number of profiles, and be good to go for a full data run end of the week / beginning next.

**Comment by s-good** [comment]
I get the same package list as you with the new pip install lines. I've started running a test on some QuOTA data. It seems that p.originator_flag_type() is set to None in all cases, causing [this line](https://github.com/IQuOD/AutoQC/blob/master/build-db.py#L66) to fail. What data are you using for your tests? 

Should we delete this check, or maybe make it optional?

**Comment by BillMills** [comment]
@s-good I'm using the batch of all quota profiles we've been using for some time - it's in our Oostende container under /AutoQC/data/quota_all.wod, or you can re-grab it from https://s3-us-west-2.amazonaws.com/autoqc/quota_all.wod

Without originator flags, we can run QC tests but we can't train our decision algorithms (`analyze_results.py` and `catchall.py`) - I've been relying on the originator flags as our gold standard truth information for validating against. If we don't have those, we'd need to train against another set of flags.

**Comment by s-good** [comment]
The line that causes the problem is checking whether there is code to say how the originator QC flags are defined (e.g. 1 = OK, 4 = bad). Ideally we would have this information and use it to interpret the originator QC flags. Without it we can still train our algorithms but we will have to manually tell the system how to interpret the flags.

**Comment by BillMills** [comment]
@s-good OK, I see what you're saying; you're thinking of a situation where `p.originator_flag_type()` is `None`, but there still are actually originator flags for each level that we can interpret later. My (perhaps poor) reasoning here was that if `p.originator_flag_type()` is not defined, then probably none of the originator flags are, either, and we wouldn't be able to train our algorithms in that case.

I'd certainly be open to confirming that originator flags exist in a different way, or not worrying about them altogether and just throwing it all at the algo and filtering down later, if computing time is no object.

**Comment by s-good** [comment]
I was wondering if we can include the file used for the AOML climatology check in the list of downloads?

**Comment by BillMills** [comment]
@s-good yes we can - I'll add that in and look into why tests are failing after work today.

**Comment by s-good** [comment]
I'll use the config defined in the install.sh so it will be numpy 1.11.1 and scipy 0.18.0. Hopefully we can get the climatology file into a better location soon.

**Pull request merged**
