### PR TITLE
cotede updates + CI passing

### PR DESCRIPTION
**Pull request by BillMills**
This PR extends and replaces #259 by updating the CoTeDe tests and CI environment to pass after making the changes suggested by @castelao in that PR.

We should expect and we do see some changes to the QC decisions made by CoTeDe due to the update to CoTeDe and oceansdb. The commits added to this PR that build upon #259 change the expected outcome for CoTeDe unit tests so that they pass by fiat, barring an a priori expected result. However, some of these changes are concerning; to sanity check them independently from the test suite, I ran AutoQC on 1000 profiles before and after this change. The CoTeDe results are as follows:

Before this PR:
```
                       NAME OF TEST   FAILS     TPR     FPR     TNR     FNR
      CoTeDe_Argo_density_inversion      81    9.4%    7.2%   92.8%   90.6%
          CoTeDe_GTSPP_WOA_normbias     295   59.2%    8.2%   91.8%   40.8%
          CoTeDe_GTSPP_global_range      62   14.6%    0.2%   99.8%   85.4%
              CoTeDe_GTSPP_gradient      80   19.2%    0.0%  100.0%   80.8%
       CoTeDe_GTSPP_profile_envelop     109   26.1%    0.0%  100.0%   73.9%
           CoTeDe_GTSPP_spike_check      26    6.2%    0.0%  100.0%   93.8%
                 CoTeDe_Morello2014     679   64.3%   70.5%   29.5%   35.7%
                CoTeDe_WOA_normbias     125   29.3%    0.5%   99.5%   70.7%
           CoTeDe_anomaly_detection     542   69.5%   43.2%   56.8%   30.5%
             CoTeDe_digit_roll_over     100   23.7%    0.2%   99.8%   76.3%
                 CoTeDe_fuzzy_logic     338   68.8%    8.7%   91.3%   31.2%
                    CoTeDe_gradient      85   20.4%    0.0%  100.0%   79.6%
        CoTeDe_location_at_sea_test       5    0.7%    0.3%   99.7%   99.3%
              CoTeDe_rate_of_change     161   30.9%    5.5%   94.5%   69.1%
                       CoTeDe_spike      10    2.4%    0.0%  100.0%   97.6%
               CoTeDe_tukey53H_norm      26    5.3%    0.7%   99.3%   94.7%
```

After this PR:

```
                       NAME OF TEST   FAILS     TPR     FPR     TNR     FNR
      CoTeDe_Argo_density_inversion      32    3.8%    2.7%   97.3%   96.2%
          CoTeDe_GTSPP_WOA_normbias     294   60.0%    7.5%   92.5%   40.0%
          CoTeDe_GTSPP_global_range      62   14.6%    0.2%   99.8%   85.4%
              CoTeDe_GTSPP_gradient      80   19.2%    0.0%  100.0%   80.8%
       CoTeDe_GTSPP_profile_envelop     109   26.1%    0.0%  100.0%   73.9%
           CoTeDe_GTSPP_spike_check     169   28.1%    8.9%   91.1%   71.9%
                 CoTeDe_Morello2014    1000  100.0%  100.0%    0.0%    0.0%
                CoTeDe_WOA_normbias     128   30.0%    0.5%   99.5%   70.0%
           CoTeDe_anomaly_detection     231   49.2%    4.5%   95.5%   50.8%
             CoTeDe_digit_roll_over     100   23.7%    0.2%   99.8%   76.3%
                 CoTeDe_fuzzy_logic    1000  100.0%  100.0%    0.0%    0.0%
                    CoTeDe_gradient      85   20.4%    0.0%  100.0%   79.6%
        CoTeDe_location_at_sea_test       4    0.5%    0.3%   99.7%   99.5%
              CoTeDe_rate_of_change     161   30.9%    5.5%   94.5%   69.1%
                       CoTeDe_spike      57   13.7%    0.0%  100.0%   86.3%
               CoTeDe_tukey53H_norm     109   25.7%    0.3%   99.7%   74.3%
```

A few jump out as immediately concerning:

## Morello2014 and fuzzy_logic

After updates, both these tests flagged every single profile in the 1000 I ran over. Furthermore, if you look at the changes necessitated in b53f8e5 in this PR to make unit testing pass for those tests, both those tests started flagging the very first level in the testing profile. In fact for `fuzzy_logic`, the first level was the *only* level where the QC decision in the unit test suite changed before and after these updates. This sets off edge-case alarm bells for me; @castelao any guesses as to what could be wrong with those two?

## Argo_density_inversion

While most CoTeDe tests in the test suite changed their decision for only about 10 levels in the testing profile (which contains over 1000 levels), `CoTeDe_Argo_density_inversion` changed its decision for 129 levels. This relatively large amount of churn isn't necessarily wrong, but is surprising enough compared to the other CoTeDe tests to be worth mentioning.

---

Beyond the ones mentioned above, the spike tests and anomaly detection show pretty big swings in the 1k profiles I looked at; again, not necessarily wrong, but comments would be interesting.

@castelao please let me know any thoughts on the above; the others may be fine, but something is certainly wrong with Morello and fuzzy_logic in the way we have them here.

### CODE REVIEW

**Comment by BillMills** [comment]
(I'll also point out that if you look at the TPR:FPR ratio after these updates, some tests are dramatically improved - great work @castelao!)

**Comment by castelao** [comment]
@BillMills , thanks! There is something strange with the fuzzy methods. I'll check it out and get back to you. Thanks for pointing that!

**Comment by BillMills** [comment]
Hi @castelao - after carefully examining a few example profiles, it seems that the problem is that the `features` object being supplied to the `fuzzylogic` function all the way up in `cotede/qc.py` has changed from one version of the code to another. 

In the old version, `features` had two keys, `spike` and `gradient`, which were masked arrays with the first and last entries masked out, I guess because spikes and gradients don't make sense at the edges of a profile.

In the new version, these are just regular arrays instead of masked arrays, and have `nan` at the start and end instead of masks. This starts causing problems for fuzzy logic at https://github.com/castelao/CoTeDe/blob/master/cotede/fuzzy/fuzzy_core.py#L43, where it expects to pass along any masks it finds to the `membership` and `rules` objects it constructs. The end result seems to be that the first and last level in all profiles get their fuzzy logic statistic overestimated, turning them into flagged data and resulting in the 100% flag rate I report above.

Does this change from masked arrays to `nan`s in the `features` object sound familiar to you? Was that intentional and fuzzylogic just needs to handle the `nan`s, or should `features` still contain masked arrays? Thanks for your attention on this, I believe this is the last thing to solve before @s-good can rerun the full analysis.

**Comment by BillMills** [comment]
@castelao @s-good see https://github.com/castelao/CoTeDe/pull/53 for a guess at resolving the problem I mention above.

**Comment by BillMills** [comment]
fd49b19 rolls this forward to CoTeDe 0.23.6, which appears bug free and produces qualitatively reasonable looking results on 1000 profiles, as recorded below. I'm happy to merge this PR here, which I may do if there's no objections; we'll rev to match future stable versions of CoTeDe as they come out.


```
      CoTeDe_Argo_density_inversion      32    3.8%    2.7%   97.3%   96.2%
          CoTeDe_GTSPP_WOA_normbias     294   60.0%    7.5%   92.5%   40.0%
          CoTeDe_GTSPP_global_range      62   14.6%    0.2%   99.8%   85.4%
              CoTeDe_GTSPP_gradient      80   19.2%    0.0%  100.0%   80.8%
       CoTeDe_GTSPP_profile_envelop     109   26.1%    0.0%  100.0%   73.9%
           CoTeDe_GTSPP_spike_check     169   28.1%    8.9%   91.1%   71.9%
                 CoTeDe_Morello2014     212   46.8%    2.9%   97.1%   53.2%
                CoTeDe_WOA_normbias     128   30.0%    0.5%   99.5%   70.0%
           CoTeDe_anomaly_detection     232   49.4%    4.5%   95.5%   50.6%
             CoTeDe_digit_roll_over     100   23.7%    0.2%   99.8%   76.3%
                 CoTeDe_fuzzy_logic     185   40.8%    2.6%   97.4%   59.2%
                    CoTeDe_gradient      85   20.4%    0.0%  100.0%   79.6%
        CoTeDe_location_at_sea_test       4    0.5%    0.3%   99.7%   99.5%
              CoTeDe_rate_of_change     161   30.9%    5.5%   94.5%   69.1%
                       CoTeDe_spike      57   13.7%    0.0%  100.0%   86.3%
               CoTeDe_tukey53H_norm     109   25.7%    0.3%   99.7%   74.3%
```

**Comment by castelao** [comment]
No objections on my side.

I just uploaded some changes on fuzzy logic that should give some notable improvements on false positives. I should be able to have a new release in the following days, but I need to extend a couple of validation tests first.

**Pull request merged**
