### PR TITLE
Performance improvement for CoTeDe

### PR DESCRIPTION
**Pull request by castelao**
Before it would call CoTeDe to run a full set of tests, like the full GTSPP recommendation, to extract only one test at a time. Now it calls CoTeDe to run only the specific test of interest.

It should make significant performance difference for most tests using CoTeDe. Since AutoQC runs in parallel, and only a portion of tests use CoTeDe, it requires a large data processing to identify this time difference.

### CODE REVIEW

**Comment by castelao** [comment]
@s-good and @BillMills , are you OK with this PR?

It says that there is a conflict, but I can't see what it is.

**Comment by BillMills** [comment]
@castelao if you on your local machine switch to your `cotedeupdate` branch, and then do `git pull upstream master` (assuming you have a remote called `upstream` pointed at this repo), git should report all the files with merge conflicts in them, and annotate them inline. Let me know if this works for you!

**Comment by castelao** [comment]
Hi @BillMills . Yes, I called upstream, and yes I usually keep them sync, like I did for the previous PR `deac0a8`. I guess these PRs took so long that i missed the opportunity to sync again. I'll work on that when I have chance.

Thanks,

**Comment by BillMills** [comment]
Hey @castelao - any luck here? Once #161 wraps up we will be ready for 1.0, and I really want this PR included there; let me know if I can help at all!

**Pull request merged**
