### PR TITLE
New QC tests

### PR DESCRIPTION
**Pull request by BillMills**
will be pushing attempts at the more straightforward of the new QC tests to this PR (more sophisticated ones will get their own feature branch).

### CODE REVIEW

**Comment by BillMills** [comment]
3f2b658:

Implements the EN_constant_value test from #49; testing validates that this implementation:
 - flags every element in a profile where 9/10 temperature measurements are the same
 - does not flag anything in a profile where 8/10 measurements are the same
 - does not flag anything in a profile where 9/10 measurements are the same, but those measurements are spread over less than 100 m.

Note only temperature (and not salinity) is examined here, per the other qc tests so far.

**Comment by s-good** [comment]
Hi @BillMills - looks good! I'm not sure what would happen if there were missing data values, though. It may just work but I think it would be good to include the check that there are valid temperature and depths at the levels as done e.g. in Argo gradient check just in case it doesn't.

**Comment by BillMills** [comment]
@s-good - agreed, implemented in b7be6f6; also, generalized testing profiles to support missing values; should include missing value validation for all qc tests. More to come shortly.

**Comment by BillMills** [comment]
Argo_impossible_date doesn't have it's time check implemented yet, need to resolve #62 first.

**Comment by BillMills** [comment]
This PR implements solutions for #49, #51, #52 and #53, including validation checks for all of the above. The only outstanding task is resolving #62, so we can finish implementing the time check in the impossible date test (#51) - otherwise this is mergable pending feedback.

**Pull request merged**
